[project]
name = "volby-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.17.8",
    "pandas>=2.0.0",
    "requests>=2.31.0",
    "pyarrow>=14.0.0",
    "plotly>=5.18.0",
]
