[project]
name = "volby-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.17.8",
    "pandas>=2.3.3",
]
